apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-image-registry-gcs
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: ImageRegistry
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  secretRef:
    name: installer-cloud-credentials
    namespace: openshift-image-registry
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    permissions:
      - storage.buckets.create
      - storage.buckets.delete
      - storage.buckets.get
      - storage.buckets.list
      - storage.buckets.createTagBinding
      - storage.buckets.listEffectiveTags
      - storage.objects.create
      - storage.objects.delete
      - storage.objects.get
      - storage.objects.list
    skipServiceCheck: true
  serviceAccountNames:
  - cluster-image-registry-operator
  - registry
